In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.metrics import (
    mean_absolute_error,
    root_mean_squared_error,
)

from forecasting import forecast_next_hours

In [2]:
df = pd.read_csv(
    "../data/raw/ed_arrivals.csv"
)

df["timestamp"] = pd.to_datetime(
    df["timestamp"]
)

df = df.sort_values(
    "timestamp"
).reset_index(drop=True)

df.head()

            timestamp  arrivals day_of_week  is_weekend  is_holiday  hour
0 2026-01-01 00:00:00         3    Thursday           0           1     0
1 2026-01-01 01:00:00         2    Thursday           0           1     1
2 2026-01-01 02:00:00         3    Thursday           0           1     2
3 2026-01-01 03:00:00         4    Thursday           0           1     3
4 2026-01-01 04:00:00         2    Thursday           0           1     4

In [3]:
print("Number of rows:", len(df))

print(
    "Start:",
    df["timestamp"].min()
)

print(
    "End:",
    df["timestamp"].max()
)

Number of rows: 8760
Start: 2026-01-01 00:00:00
End: 2026-12-31 23:00:00

In [4]:
test_index = len(df) - 13

history = df.iloc[:test_index].copy()

actual_future = df.iloc[
    test_index:test_index + 12
].copy()

print("Last historical timestamp:")
print(history["timestamp"].iloc[-1])

print("\nActual future:")
print(actual_future[
    ["timestamp", "arrivals"]
])

Last historical timestamp:
2026-12-31 10:00:00

Actual future:
               timestamp  arrivals
8747 2026-12-31 11:00:00         7
8748 2026-12-31 12:00:00         4
8749 2026-12-31 13:00:00         7
8750 2026-12-31 14:00:00         8
8751 2026-12-31 15:00:00         8
8752 2026-12-31 16:00:00        11
8753 2026-12-31 17:00:00         9
8754 2026-12-31 18:00:00         9
8755 2026-12-31 19:00:00        12
8756 2026-12-31 20:00:00         6
8757 2026-12-31 21:00:00         7
8758 2026-12-31 22:00:00         3

In [5]:
prediction = forecast_next_hours(
    history=history,
    hours=12,
)

prediction

             timestamp  predicted_arrivals
0  2026-12-31 11:00:00                6.52
1  2026-12-31 12:00:00                6.81
2  2026-12-31 13:00:00                7.73
3  2026-12-31 14:00:00                7.07
4  2026-12-31 15:00:00                6.66
5  2026-12-31 16:00:00               10.20
6  2026-12-31 17:00:00                9.41
7  2026-12-31 18:00:00                9.70
8  2026-12-31 19:00:00                9.71
9  2026-12-31 20:00:00                7.18
10 2026-12-31 21:00:00                6.63
11 2026-12-31 22:00:00                3.00

In [6]:
comparison = actual_future[
    ["timestamp", "arrivals"]
].merge(
    prediction,
    on="timestamp",
    how="inner"
)

comparison

             timestamp  arrivals  predicted_arrivals
0  2026-12-31 11:00:00         7                6.52
1  2026-12-31 12:00:00         4                6.81
2  2026-12-31 13:00:00         7                7.73
3  2026-12-31 14:00:00         8                7.07
4  2026-12-31 15:00:00         8                6.66
5  2026-12-31 16:00:00        11               10.20
6  2026-12-31 17:00:00         9                9.41
7  2026-12-31 18:00:00         9                9.70
8  2026-12-31 19:00:00        12                9.71
9  2026-12-31 20:00:00         6                7.18
10 2026-12-31 21:00:00         7                6.63
11 2026-12-31 22:00:00         3                3.00

In [7]:
mae = mean_absolute_error(
    comparison["arrivals"],
    comparison["predicted_arrivals"]
)

print("12-hour forecast MAE:", mae)

12-hour forecast MAE: 1.0033333333333332

In [8]:
rmse = root_mean_squared_error(
    comparison["arrivals"],
    comparison["predicted_arrivals"]
)

print("12-hour forecast RMSE:", rmse)

12-hour forecast RMSE: 1.271200220264298

In [9]:
print(comparison)
print("MAE:", mae)
print("RMSE:", rmse)

             timestamp  arrivals  predicted_arrivals
0  2026-12-31 11:00:00         7                6.52
1  2026-12-31 12:00:00         4                6.81
2  2026-12-31 13:00:00         7                7.73
3  2026-12-31 14:00:00         8                7.07
4  2026-12-31 15:00:00         8                6.66
5  2026-12-31 16:00:00        11               10.20
6  2026-12-31 17:00:00         9                9.41
7  2026-12-31 18:00:00         9                9.70
8  2026-12-31 19:00:00        12                9.71
9  2026-12-31 20:00:00         6                7.18
10 2026-12-31 21:00:00         7                6.63
11 2026-12-31 22:00:00         3                3.00
MAE: 1.0033333333333332
RMSE: 1.271200220264298